jenkinsci/pipeline-utility-steps-plugin

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/mf/ReadManifestStepExecution.java

fixes error with text encodinf of Manifest

---

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/maven/ReadMavenPomStep.java

adds null protection in case of classes have no package.

---

src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/zip/UnZipStep/help-dir.html

The help message for unzip directory appears to have been copied from zip directory.

Fix help message for unzip directory.

---

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/UnZipStepExecution.java

I fixed the issue I created in JIRA by closing the output streams of the files extracted by the zip file. This resolves the issues I had with the plugin.
As the second commit I did some improvements to the general unzipping code regarding the load generated on the GC. Closing the input streams for the zip entries is not required by all means, because they are closed once the zip file closes. How ever closing the streams means that the parent zip class is able to reuse the Inflater objects that are rather expensive to create.
Also I replaced some of the code with the the counter part from `IOUtils` just to clean it up a little.
If you want to merge both my pull requests, you can also just pull in my master branch. I already resolve the merge conflict there.

[JENKINS-34927] Close streams of extracted files

---

docs/STEPS.md
pom.xml
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/WriteYamlStep.java
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/conf/WriteYamlStep/config.jelly
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/conf/WriteYamlStep/config.properties
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/conf/WriteYamlStep/help.html
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/WriteYamlStepTest.java
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/WriteYamlStepUnitTest.java

Delegates to snakeyaml the task of serializing any Object to a yaml file

Implemented writeYaml step

---

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadPropertiesStepExecution.java

After using readProperties on Windows, the file was still locked and could not be deleted until a restart of Jenkins. A try-block around the InputStream is preventing this.

Adding try-block to avoid locking on Windows systems

---

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadPropertiesStepExecution.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/mf/ReadManifestStepExecution.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/maven/ReadMavenPomStep.java

adding try-with-resource blocks to FilePath#read calls
The opened InputStreams now get closed automatically and do not leak file handles anymore

JENKINS-43568: readProperties java.exe locks properties file

---

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/AbstractFileOrTextStep.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/AbstractFileOrTextStepDescriptorImpl.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/AbstractFileOrTextStepExecution.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadPropertiesStep.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadPropertiesStepExecution.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadYamlStep.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/mf/ReadManifestStep.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/mf/ReadManifestStepExecution.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/json/ReadJSONStep.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/json/ReadJSONStepExecution.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/json/WriteJSONStepExecution.java
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/Messages.properties
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/json/Messages.properties
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadPropertiesStepTest.java
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadYamlStepTest.java
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/json/ReadJSONStepTest.java
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/mf/ReadManifestStepTest.java

* Created abstract base classes for read steps to remove duplication.
* Updated tests to not allocate node while reading text.

Don't require workspace for reading from text parameter.

---

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/FileSha1Step.java
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/fs/FileSha1Step/config.groovy
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/fs/FileSha1Step/help-file.html
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/fs/FileSha1Step/help.html
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/FileSha1StepTest.java

This can be useful under many circumstances, in particular when building docker images containing some kind of cache for a package manager.

Add support for sha1 step to hash files

---

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/json/WriteJSONStep.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/json/WriteJSONStepExecution.java
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/json/WriteJSONStep/help.html
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/json/WriteJSONStepTest.java

The pretty parameter (if defined and greater than 0) will reflect the number of spaces to indent the final file (obviously, whilst prettyfing it)

[JENKINS-47347] accept an optional pretty parameter for writeJSON step

---

pom.xml
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/TeeStep.java
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/fs/TeeStep/config.jelly
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/TeeStepTest.java

Targeted to https://github.com/jenkinsci/pipeline-utility-steps-plugin/pull/36.
@reviewbybees

Porting https://github.com/jglick/tee-step-plugin to pipeline-utility-steps

---

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/jenkins/NodesByLabelStep.java
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/Messages.properties
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/jenkins/NodesByLabelStep/config.jelly
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/jenkins/NodesByLabelStep/help.html
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/jenkins/NodesByLabelStepTest.java

We have this step in our shared library.
The step enables us to maintain a group of nodes through Jenkins by using their label to get the desired group, ie. 'MacOS' label.
Currently, our shared library step is using the Jenkins JSON API, earlier it was using unsafe groovy methods.
So I suggest we add the step to this plugin 👍 
The 'nodesByLabel' is open for better suggestion, also the package location.

Add nodes by label step

---

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/mf/ReadManifestStepExecution.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/UnZipStep.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/UnZipStepExecution.java
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/zip/UnZipStep/config.groovy
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/zip/UnZipStep/help-quiet.html
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/UnZipStepTest.java

As mentioned in [JENKINS-40518](https://issues.jenkins-ci.org/browse/JENKINS-40518), using the unzip step results in every file dealt with being logged, which can make logs large and annoying to read. This PR adds a boolean option 'quiet' to the unzip step, which when true turns off said logging and instead prints a total file count when done. By default quiet is false.

Feature: Added the ability to suppress verbose logging during unzip step

---

pom.xml
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadPropertiesStep.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadPropertiesStepExecution.java
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadPropertiesStep/help.html
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadPropertiesStepTest.java

It adds support for interpolated variables like 
var1 = value1
var2 = ${var1}-value2
It will also expand ${sys:...} and ${env:...} keys.
As a draw back it increase the size of the pull-in because of the extra three libraries form Apache Commons.
Reference : http://commons.apache.org/proper/commons-configuration/userguide/howto_utilities.html#Utility_classes_and_Tips_and_Tricks

Added support for interpolated variables

---

Jenkinsfile
pom.xml
src/findbugs/excludesFilter.xml
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadPropertiesStepExecution.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/WriteYamlStep.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/mf/ReadManifestStepExecution.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/FileSha1Step.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/FindFilesStepExecution.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/TeeStep.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/TouchStep.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/jenkins/NodesByLabelStep.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/json/ReadJSONStepExecution.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/json/WriteJSONStepExecution.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/maven/ReadMavenPomStep.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/maven/WriteMavenPomStep.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/UnZipStepExecution.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/ZipStepExecution.java
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/conf/WriteYamlStep/config.jelly
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/conf/WriteYamlStep/config.properties
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/conf/WriteYamlStep/help.html

The excludesFile is not taking effect as it is configured in plugin-pom, so needed a full config in here.

Fixing findbugs warnings after plugin pom upgrade

---

src/main/resources/META-INF/hudson.remoting.ClassFilter

It is just a hotfix for https://github.com/jenkinsci/jenkins/pull/3359, which prevents the bug from appearing in `findFiles()` Pipeline Step on 2.107.1 and 2.102...2.112
@reviewbybees @jglick

[JENKINS-50237] - Apply workaround while Jenkins Core is not fixed/backported

---

Jenkinsfile
pom.xml
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/maven/WriteMavenPomStep.java
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/mf/ReadManifestStepTest.java
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/maven/WriteMavenPomStepTest.java

Just enables CI for 2.107.1 in order to enable testing of potential JEP-200 regressions.
https://issues.jenkins-ci.org/browse/JENKINS-50633
Downstream of https://github.com/jenkinsci/workflow-cps-plugin/pull/218
@reviewbybees @rsandell

[JENKINS-50633] - Update Pipeline: CPS requirement to 2.48 and run tests against core with JEP-200

---

pom.xml

This commit updates maven-model to workaround https://issues.apache.org/jira/browse/MNG-6204 .
The problem arise when using method readMavenPom() on a *large* pom containing m2e specific annotations ( <?m2e ignore?>, see http://www.eclipse.org/m2e/documentation/release-notes-17.html#new-syntax-for-specifying-lifecycle-mapping-metadata ).
Jenkins failed with no really usefull error message.

Updated maven-model version to workaround MNG-6204

---

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadPropertiesStepExecution.java
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadPropertiesStepTest.java

We've had some situations in which we needed to specify defaults and be included in variable interpolation. For example a default could be a parametrized path to certain resources, while the loaded properties file would simply contain the referenced variables, i.e.:
default as hashmap:
`[base_path: "/${application}/${environment}/${version}"]`
loaded properties file
```
application=My Application
environment=DEV
version=1.0.0
```
Current workaround would be to serialize this hashmap into a string and provide this to the readProperties method, but this seems the be a convoluted approach. This tweaks allows you to use the defaults parameter and have those defaults be included into the string interpolation.

Include defaults in interpolation

---

src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/TeeStepTest.java

Fixes a test which passed in #51 PR builds but fails in master due to a workspace name which happens to start with a `u`, sigh. I tried `.replace("\\u", "\\U")` and probably could have used `.replace('\\', '/')` but in the end it seemed clearer and safer to pass in the file path via other means.

Dollar-slashy strings are not that safe

---

Jenkinsfile

Using the feature introduced in https://github.com/jenkins-infra/pipeline-library/pull/79
Similar to https://github.com/jenkinsci/buildtriggerbadge-plugin/pull/34 and https://github.com/jenkinsci/label-verifier-plugin/pull/4
@jenkinsci/java11-support @rsandell

Also build the plugin with JDK11 on recent core

---

pom.xml
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/UnZipStepExecution.java

Amends #60. @batmat @rsandell @dwnusbaum

[JENKINS-55759] Updates

---

Jenkinsfile
pom.xml
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/shaded/org/yaml/snakeyaml/nodes/Tag.java

[JENKINS-54355](https://issues.jenkins-ci.org/browse/JENKINS-54355)
Tag.java has references to classes which are not longer available in Java 11, without a module addition. This could cause problem when running this plugin on a Jenkins with Java 11.
@jenkinsci/java11-support

[JENKIKNS-54355] Dynamically load java.sql classes

---

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/jenkins/NodesByLabelStep.java

While perusing the source tree, I noticed a deprecated method:
- The documentation for [`Jenkins.getInstance()`](https://javadoc.jenkins-ci.org/jenkins/model/Jenkins.html#getInstance--) states: "This is a historical alias for [`getInstanceOrNull()`](https://javadoc.jenkins-ci.org/jenkins/model/Jenkins.html#getInstanceOrNull--) but with ambiguous nullability. Use [`get()`](https://javadoc.jenkins-ci.org/jenkins/model/Jenkins.html#get--) in typical cases."
We always call `getLabels()` on the result, so the code assumes that the result is non-null. Therefore `Jenkins.get()` is more appropriate to use here rather than `Jenkins.getInstanceOrNull()`. So I changed the code to use `Jenkins.get()`.

Remove usages of deprecated APIs

---

src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadYamlStepTest.java
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/FileSha1StepTest.java
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/TouchStepTest.java
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/UnZipStepTest.java
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/ZipStepTest.java

While looking at the test suite for this plugin, I noticed the `CpsFlowDefinition`s in the tests don't consistently use the script security sandbox. Always using the script security sandbox makes the tests consistent with each other, and it's also a more realistic environment given that the script security sandbox should always be enabled in production.
In this change, I enabled the script security sandbox wherever it was previously disabled. In some cases, comments had been left stating that the script security sandbox had been disabled to work around some bugs in the Script Security plugin. These bugs seem to have now been resolved, since the tests now pass when using the sandbox.

Consistently use sandbox for CpsFlowDefinitions

---

pom.xml
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/ZipStepTest.java

Bumps the [plugin parent POM](https://github.com/jenkinsci/plugin-pom) from 3.48 to 3.54.
See [the changelog](https://github.com/jenkinsci/plugin-pom/releases) and the full diff in [the compare view](https://github.com/jenkinsci/plugin-pom/compare/plugin-3.48...plugin-3.54).

Bump plugin parent POM

---

src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/fs/FindFilesStep/config.groovy

Exclusion textbox didn't bind correctly to the property "excludes" of the findfiles class resulting in a generated script missing the exclusion entered by the user.
Fixed by modifying the underlying field name to match the field from the FindFiles class

findFiles exclusions textbox fix

---

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/json/ReadJSONStep.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/json/ReadJSONStepExecution.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/json/WriteJSONStep.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/json/WriteJSONStepExecution.java
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/json/ReadJSONStep/config.jelly
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/json/ReadJSONStep/config.properties
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/json/ReadJSONStep/help-returnPojo.html
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/json/WriteJSONStep/help.html
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/json/ReadJSONStepTest.java
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/json/WriteJSONStepTest.java

The documentation of readJSON suggests that readJSON returns plain Java objects (like readYaml does), but they are of type net.sf.json.JSON and some members of that are not whitelisted, so it is painful to work with... Additionally null values encountered in the JSON are deserialized by json-lib into either JSONNull instances or JSONObject instances with isNullObject() == true. Either way non null references that brings strange errors while looping through the data structure as Map and or List.
This contribution fixes this by still using json-lib to parse the JSON string, but then transforms the resulting JSONObject or JSONArray into plain Java datastructures LinkedHashMap and ArrayList (which are the Java objects Groovy uses for its Map `[:]` and List `[]`).
Consequently writeJSON had to …

[JENKINS-53015] readJson return plain Java objects

---

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/TeeStep.java
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/TeeStepTest.java

This is just a followup of #62 
Most credits of changes going out to @tolnaisz
Just fixed the test error mentioned in #62

[JENKINS-54346] && [JENKINS-55505] Fix stream handling in tee (followup)

---

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/TeeStep.java
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/TeeStepTest.java

Based on work from roel0 this change hopefully fixes the tee issue. It opens the stream only once and closes it at the end of the tee step.
The underlying file gets created and truncated. This is different from the current behavior but I think it is the right one as tee by default (re-)creates the file so it contains only the content tee'd into it.

[JENKINS-54346] && [JENKINS-55505] Fix stream handling in tee.

---

CHANGES.md
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/ZipStep.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/ZipStepExecution.java
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/zip/ZipStep/config.groovy
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/zip/ZipStep/help-overwrite.html
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/ZipStepTest.java

Added the possibility to overwrite the zip file in cases where the destination file already exists.

[JENKINS-42591] && [JENKINS-47060] Add overwrite option to zip step.

---

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/ZipStepExecution.java
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/ZipStepTest.java

Hello,
Currently, when running a pipeline creating a ZIP and specifying "overwrite: true", if the destination file doesn't exist, it will throw an IOException. I've run into this issue often when running a pipeline for the first time, or after clearing a workspace.
The original pull request (https://github.com/jenkinsci/pipeline-utility-steps-plugin/pull/76) checked if the ZIP existed prior to attempting to delete, however this was lost after feedback encouraging converting to NIO2 file APIs, where it now throws an IOException. This pull request changes the functionality to be more like the original.
Return value of Files.deleteIfExists is ignored, as it indicates if the file existed or not, and for overwriting I don't believe we mind either way.
Thanks

Removing IOException when using ZIP with "overwrite: true", and the ZIP doesn't currently exist

---

docs/STEPS.md
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/WriteYamlStep.java
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/conf/WriteYamlStep/config.jelly
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/conf/WriteYamlStep/config.properties
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/conf/WriteYamlStep/help.html
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/WriteYamlStepTest.java

Adds a `returnText` boolean parameter to `writeYaml` so it returns the yaml as a string rather than writing it to a file.

[JENKINS-63719] add returnText option to writeYaml

---

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/ZipStepExecution.java
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/ZipStepTest.java

[JENKINS-62928](https://issues.jenkins.io/browse/JENKINS-62928) Zip step hangs as it tries to recursively zip the archive being created. That seems to be caused by https://github.com/jenkinsci/pipeline-utility-steps-plugin/commit/c093b94d2ef3dc7f8b2329d397f7ca3cc27664a7. We do not compare canonical paths anymore, which causes the zip step to consider the zip it is currently creating: the process hangs and produces a very big corrupted zip file.

[JENKINS-62928] Zip step should test canonical paths

---

docs/STEPS.md
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/json/WriteJSONStep.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/json/WriteJSONStepExecution.java
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/json/Messages.properties
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/json/WriteJSONStep/help.html
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/jenkins/NodesByLabelStepTest.java
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/json/WriteJSONStepTest.java

Adds a `returnText` boolean parameter to `writeJSON` so it returns the json as a string rather than writing it to a file.

[JENKINS-63720] add returnText option to writeJSON

---

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/WriteYamlStep.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/json/WriteJSONStep.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/json/WriteJSONStepExecution.java
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/WriteYamlStepTest.java
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/json/WriteJSONStepTest.java

Allow `writeYaml` and `writeJSON` to run with `returnText: true` without requiring a node. This is the same way that `readYaml` and `readJSON` work when using the `text` parameter.

allow writeYaml and writeJSON to return text without requiring a node

---

pom.xml

I updated plugin pom to 4.6 and set min jenkins to 2.204.1, since 96% of the latest version use a newer version or this [pluginversions stats](https://stats.jenkins.io/pluginversions/pipeline-utility-steps.html)

updated plugin pom to 4.6 and set min jenkins to 2.204.1

---

src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadYamlStepTest.java
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/WriteYamlStepUnitTest.java
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/csv/WriteCSVStepTest.java
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/mf/ReadManifestStepTest.java
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/TeeStepTest.java
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/json/WriteJSONStepTest.java
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/maven/WriteMavenPomStepTest.java

Replaces some calls to deprecated methods replaced.

Deprecated API usages replaced

---

src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/TeeStepTest.java

We seem to be generally preferring `JenkinsSessionRule` to `RestartableJenkinsRule`. The main benefit to `JenkinsSessionRule` is that `#then` runs immediately, so it plays nicely with things like `@After.`

Migrate from `RestartableJenkinsRule` to `JenkinsSessionRule`

---

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/AbstractFileOrTextStepDescriptorImpl.java
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/json/ReadJSONStepTest.java

Supersedes #104. @bwalding @imonteroperez
Note that if you were bitten by this issue, you were probably writing your Pipeline script using poor practices to begin with. For example,
```groovy
def json = sh returnStdout: true, script: 'something-yielding-secret-JSON'
def object = readJSON text: json
```
can be rewritten as a first step to
```groovy
def object
try {
sh 'mkdir -p $WORKSPACE_TMP  && something-yielding-secret-JSON > $WORKSPACE_TMP/secret.json'
object = readJSON file: "$WORKSPACE_TMP/secret.json"
} finally {
sh 'rm -f $WORKSPACE_TMP/secret.json'
}
```
but better still is to never have this secret JSON text pass through Pipeline script at all:
```groovy
sh 'something-yielding-secret-JSON | something-using-secret-JSON'
```
(Pipeline does not expect actual secrets to ever be …

`argumentsToString` should never reflect `text: 'stuff'`

---

src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/mf/ReadManifestStepTest.java

https://github.com/jenkinsci/remoting/pull/532#discussion_r867287966
Not exactly sure why this test case even exists; its functionality seems to be adequately covered by other cases.

Make `ReadManifestStepTest.testRemotingJar` pass on post-JWS Remoting

---

src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/csv/ReadCSVStep/help.html

Trivial fix for the help.html on ReadCSVStep
* variable naming
* `.withHeader()` consumes the first record, so there is only one data record which has index `[0]`
- ~Link to relevant issues in GitHub or Jira~
- ~Link to relevant pull requests, esp. upstream and downstream changes~
- ~Ensure you have provided tests - that demonstrates feature works or fixes the issue~

fix help for ReadCSVStep

---

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/WriteYamlStep.java

Switch in [#149](https://github.com/jenkinsci/pipeline-utility-steps-plugin/pull/149) top use SnakeYAML API plugin also updated version of that plugin. And there was change in SplitLines from false to true. But this breaks up several functions for us. For example:
```
options:  "abc  sfksajfkl  jfajfkjakj  jqjlkkalkl  kajklfjalkd"
```
is then written to file in plugin version 2.13.0:
```
options:  "abc  sfksajfkl  jfajfkjakj  
\ jqjlkkalkl  kajklfjalkd"
```
is then written to file in plugin version 2.12.2:
```
options:  "abc  sfksajfkl  jfajfkjakj jqjlkkalkl  kajklfjalkd"
```
This pull request fix utility pipeline to its previous behavior.

Set split lines for writeYaml to false

---

pom.xml

It would be nice to use a pinned version for the dependency commons-lang3-api. My value is the latest version, as listed here: https://plugins.jenkins.io/commons-lang3-api/ 
Dependabot should be able to raise the version in the future. We are currently having problems with dependencies of other Jenkins plugins that use version 3.12.0-36.vd97de6465d5b_ of commons-lang3-api. This project is forcing 3.12.0.0.
Mainly because our company Jenkins has limited internet access.

use pinned version for commons-lang3-api

---

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadYamlStep.java

Without dropping support for SnakeYAML 1.33, add support for SnakeYAML 2.0. The only difference is that a few deprecated constructors were deleted. Resolved the problem by inlining the deleted code, which does not change any behavior. Tested by running `mvn clean verify` locally with both versions of SnakeYAML.

Forward compatibility with SnakeYAML 2.0

---

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadYamlStep.java
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadYamlStep/help.groovy
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadYamlStepTest.java

Since the upgrade to SnakeYAML 1.32 it is not possible to read YAML files greater than 3MB. This PR adds the new, optional  attribute `codePointLimit` to `readYaml`. This makes it possible to work around this limitation.
- https://bitbucket.org/snakeyaml/snakeyaml/issues/547/restrict-the-size-of-incoming-data
- https://bitbucket.org/snakeyaml/snakeyaml/commits/72dfa9f1074abe2b8a6c8776bee4476b0aed02e3
- https://bitbucket.org/snakeyaml/snakeyaml/commits/440d98e2ebd586aafd9034fc74a2a47c656eb0ce

[JENKINS-71077] Allow overriding codePointLimit to allow reading larger yaml files

---

pom.xml
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/FindFilesStepExecution.java

Without dropping compatibility with Guice 6 (currently delivered by Jenkins core), add support for Guice 7.

Forward compatibility with Guice 7

---

pom.xml

See [this thread](https://groups.google.com/g/jenkinsci-dev/c/dRY7NYuvLkM/m/8v65Z2MsAgAJ). Currently, this PR results in no change in behavior, since it adds a library plugin that will be unused at runtime, because core's copy will take precedence. But when Commons Compress is eventually removed from core, this linkage will allow this plugin to continue working. It will also allow us to update Commons Compress library plugin to recent versions, satisfying the Commons Lang 3 dependency via a plugin-to-plugin dependency between the Commons Compress library plugin and the Commons Lang 3 library plugin.
`mvn clean verify -Dtest=InjectedTest`

Add dependency on Commons Compress library plugin

---

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/TeeStep.java

According to the jenkins doc about Using anonymous classes in remoting (https://www.jenkins.io/doc/developer/extensibility/serialization-of-anonymous-classes/#usages-in-remoting), it is better to use a private static class, as anonymous classes sometimes have issues being sent across remoting. This changes the anonymous class to a private static class so the TeeStep works correctly across remoting channels.
Ran the full test suite as well as installing on a test server and running several workloads.
```[tasklist]
```

Fix issue with TeeStep and remoting

---

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadPropertiesStep.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadPropertiesStepExecution.java
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadPropertiesStep/config.jelly
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadPropertiesStep/config.properties
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadPropertiesStep/help.html
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadPropertiesStepTest.java

Signed-off-by: bright.ma RMSH06 <bright.ma@blackshark.com>
add one param to set  charset  when read Properties file

add one param to set charset when read Properties file

---

pom.xml

PCT caught a regression in the latest release, but only on the 2.426.x line:
```
java.lang.NoSuchMethodError: 'long org.apache.commons.io.IOUtils.skip(java.io.InputStream, long, java.util.function.Supplier)'
at org.apache.commons.compress.utils.IOUtils.skip(IOUtils.java:282)
at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextTarEntry(TarArchiveInputStream.java:409)
at hudson.FilePath.readFromTar(FilePath.java:3081)
at hudson.FilePath.copyRecursiveTo(FilePath.java:2866)
at jenkins.model.StandardArtifactManager.archive(StandardArtifactManager.java:73)
at org.jenkinsci.plugins.pipeline.utility.steps.CompressStepExecution.run(CompressStepExecution.java:109)
at org.jenkinsci.plugins.pipeline.utility.steps.zip.ZipStepExecution.run(ZipStepExecution.java:64)
at …
```

Require 2.440.3 or newer

---

docs/STEPS.md
pom.xml
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/toml/ReadTOMLStep.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/toml/ReadTOMLStepExecution.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/toml/WriteTOMLStep.java
src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/toml/WriteTOMLStepExecution.java
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/toml/Messages.properties
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/toml/ReadTOMLStep/config.jelly
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/toml/ReadTOMLStep/config.properties
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/toml/ReadTOMLStep/help-file.html
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/toml/ReadTOMLStep/help-text.html
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/toml/ReadTOMLStep/help.html
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/toml/WriteTOMLStep/config.jelly
src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/toml/WriteTOMLStep/help.html
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/toml/ReadTOMLStepTest.java
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/toml/WriteTOMLStepTest.java

Add steps to work with TOML files/text. We are going to use these new steps to work with BuildKit configuration files in own pipeline/shared library. The realization is similar to JSON steps.
I chose `com.fasterxml.jackson.dataformat.jackson-dataformat-toml`, because this library implements the latest version of TOML specification (v1.0.0) and was recommended by [official WIKI](https://github.com/toml-lang/toml/wiki#toml-v100).
Test cases are similar to JSON realization.

Add steps to read and write TOML file

---

src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/conf/WriteYamlStep/help.html

This PR fixes the outdated link available in the pipeline utility step pages .

fix:link correction in pipeline utility steps page

---

pom.xml

Commons compress was removed from core
Not needed since 2.492.1
mvn clean install

Commons compress was removed from core

---

pom.xml
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadYamlStepTest.java
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/WriteYamlStepUnitTest.java
src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/TeeStepTest.java

To prevent regressions when adding new tests, https://github.com/jenkinsci/plugin-pom/pull/1178 introduced a new flag that enables a Maven Enforcer rule banning `org.junit.*` imports while allowing `org.junit.jupiter.*`.
With this change, the build will fail if any `org.junit.*` imports are introduced.
My migration tool also proposed some minor fixes I included in this PR.
None. Rely on `ci.jenkins.io`.

Ban JUnit 4 imports
