src/main/java/org/jenkinsci/plugins/workflow/utility/steps/fs/FileWrapper.java, src/main/java/org/jenkinsci/plugins/workflow/utility/steps/fs/FindFilesStep.java, src/main/java/org/jenkinsci/plugins/workflow/utility/steps/fs/FindFilesStepExecution.java, src/main/resources/org/jenkinsci/plugins/workflow/utility/steps/fs/FindFilesStep/config.groovy, src/main/resources/org/jenkinsci/plugins/workflow/utility/steps/fs/FindFilesStep/help-glob.html, src/main/resources/org/jenkinsci/plugins/workflow/utility/steps/fs/FindFilesStep/help.html, src/test/java/org/jenkinsci/plugins/workflow/utility/steps/fs/FindFilesStepTest.java
=> Find files Step

.gitignore, pom.xml, src/main/java/org/jenkinsci/plugins/workflow/utility/steps/zip/UnZipStep.java, src/main/java/org/jenkinsci/plugins/workflow/utility/steps/zip/UnZipStepExecution.java, src/main/java/org/jenkinsci/plugins/workflow/utility/steps/zip/ZipStep.java, src/main/java/org/jenkinsci/plugins/workflow/utility/steps/zip/ZipStepExecution.java, src/main/resources/org/jenkinsci/plugins/workflow/utility/steps/zip/UnZipStep/config.groovy, src/main/resources/org/jenkinsci/plugins/workflow/utility/steps/zip/UnZipStep/help-dir.html, src/main/resources/org/jenkinsci/plugins/workflow/utility/steps/zip/UnZipStep/help-glob.html, src/main/resources/org/jenkinsci/plugins/workflow/utility/steps/zip/UnZipStep/help-read.html, src/main/resources/org/jenkinsci/plugins/workflow/utility/steps/zip/UnZipStep/help-test.html, src/main/resources/org/jenkinsci/plugins/workflow/utility/steps/zip/UnZipStep/help-zipFile.html, src/main/resources/org/jenkinsci/plugins/workflow/utility/steps/zip/UnZipStep/help.html, src/main/resources/org/jenkinsci/plugins/workflow/utility/steps/zip/ZipStep/config.groovy, src/main/resources/org/jenkinsci/plugins/workflow/utility/steps/zip/ZipStep/help-archive.html, src/main/resources/org/jenkinsci/plugins/workflow/utility/steps/zip/ZipStep/help-dir.html, src/main/resources/org/jenkinsci/plugins/workflow/utility/steps/zip/ZipStep/help-glob.html, src/main/resources/org/jenkinsci/plugins/workflow/utility/steps/zip/ZipStep/help-zipFile.html, src/main/resources/org/jenkinsci/plugins/workflow/utility/steps/zip/ZipStep/help.html, src/test/java/org/jenkinsci/plugins/workflow/utility/steps/zip/UnZipStepTest.java, src/test/java/org/jenkinsci/plugins/workflow/utility/steps/zip/ZipStepTest.java
=> Zip and UnZip steps

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadPropertiesStep.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadPropertiesStepExecution.java, src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadPropertiesStep/config.jelly, src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadPropertiesStep/help.html, src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadPropertiesStepTest.java
=> ReadProperties Step

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/mf/ReadManifestStep.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/mf/ReadManifestStepExecution.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/mf/SimpleManifest.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/UnZipStepExecution.java, src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/conf/mf/ReadManifestStep/config.groovy, src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/conf/mf/ReadManifestStep/help-file.html, src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/conf/mf/ReadManifestStep/help-text.html, src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/conf/mf/ReadManifestStep/help.html, src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/mf/ReadManifestStepTest.java, src/test/resources/org/jenkinsci/plugins/pipeline/utility/steps/conf/mf/testmanifest.mf
=> Read manifest Step

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/FileWrapper.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/TouchStep.java, src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/fs/TouchStep/config.groovy, src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/fs/TouchStep/help-file.html, src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/fs/TouchStep/help-timestamp.html, src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/fs/TouchStep/help.html, src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/TouchStepTest.java
=> Touch Step

docs/STEPS.md, pom.xml, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/maven/ReadMavenPomStep.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/maven/WriteMavenPomStep.java, src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/maven/ReadMavenPomStep/config.groovy, src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/maven/ReadMavenPomStep/help-file.html, src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/maven/ReadMavenPomStep/help.html, src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/maven/WriteMavenPomStep/config.jelly, src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/maven/WriteMavenPomStep/help.html, src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/maven/WriteMavenPomStepTest.java
@reviewbybees 
Could the maven dependency break the maven plugin or be broken by the maven plugin?
=> Steps to read and write maven pom files

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/maven/ReadMavenPomStep.java
=> adds null protection to ReadMavenPomStep whitelist.

CHANGES.md, pom.xml, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadYamlStep.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/mf/ReadManifestStepExecution.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/shaded/org/yaml/snakeyaml/constructor/AbstractConstruct.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/shaded/org/yaml/snakeyaml/constructor/BaseConstructor.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/shaded/org/yaml/snakeyaml/events/Event.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/shaded/org/yaml/snakeyaml/events/ScalarEvent.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/shaded/org/yaml/snakeyaml/external/com/google/gdata/util/common/base/Escaper.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/shaded/org/yaml/snakeyaml/external/com/google/gdata/util/common/base/PercentEscaper.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/shaded/org/yaml/snakeyaml/external/com/google/gdata/util/common/base/UnicodeEscaper.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/shaded/org/yaml/snakeyaml/introspector/MissingProperty.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/shaded/org/yaml/snakeyaml/nodes/Node.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/shaded/org/yaml/snakeyaml/nodes/ScalarNode.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/shaded/org/yaml/snakeyaml/parser/Parser.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/shaded/org/yaml/snakeyaml/representer/Representer.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/shaded/org/yaml/snakeyaml/scanner/Scanner.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/UnZipStep.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/UnZipStepExecution.java, src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/zip/UnZipStep/config.groovy, src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/zip/UnZipStep/help-charset.html, src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/UnZipStepTest.java
I had an issue with the unzip step in the Pipeline, getting a malformed exception. Apon investigation our ANT scripts do the zip, something which cannot be easily removed, I have added the option to the plugin to specify the charset, which works perfectly with my solution.
=> Feature: Added the ability to unzip ZIP files not using UTF-8.

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/ZipStepExecution.java, src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/mf/ReadManifestStepTest.java, src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/FindFilesStepTest.java, src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/ZipStepTest.java
=> [JENKINS-34122] Exclude output file from itself

pom.xml, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/maven/ReadMavenPomStep.java, src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/maven/WriteMavenPomStepTest.java
Noticed during review of #36. I do not care if this is incompatible. More important to fix this bad dependency.
@reviewbybees
=> Removing runtime dep on workflow-cps

pom.xml, src/findbugs/excludesFilter.xml, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/AbstractFileOrTextStep.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/AbstractFileOrTextStepDescriptorImpl.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/AbstractFileOrTextStepExecution.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadPropertiesStep.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadPropertiesStepExecution.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadYamlStep.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/WriteYamlStep.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/mf/ReadManifestStep.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/mf/ReadManifestStepExecution.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/FileSha1Step.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/FindFilesStep.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/FindFilesStepExecution.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/TeeStep.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/TouchStep.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/json/ReadJSONStep.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/json/ReadJSONStepExecution.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/json/WriteJSONStep.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/json/WriteJSONStepExecution.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/maven/ReadMavenPomStep.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/maven/WriteMavenPomStep.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/UnZipStep.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/UnZipStepExecution.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/ZipStep.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/ZipStepExecution.java, src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/fs/TeeStep/config.jelly, src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/WriteYamlStepTest.java, src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/mf/ReadManifestStepTest.java, src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/TeeStepTest.java
And adapt to new conventions for writing steps.
@reviewbybees 
@jenkinsci/code-reviewers
=> Upgrade to new plugin pom structure

src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/fs/TeeStep/config.jelly, src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/TeeStepTest.java
Corrects a buglet from #37.
@reviewbybees @bpedersen2
=> Fixed snippetizer for TeeStep

.mvn/extensions.xml, .mvn/maven.config, Jenkinsfile, pom.xml, src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/TeeStepTest.java
Updating dependencies enough to pick up JEP-210 and check the `tee` step more aggressively with `DurableTaskStep` in watching mode.
@rsandell @abayer @svanoort @dwnusbaum @joseblas
=> [JEP-210] Verifying that the tee step works correctly with remote durable task output

pom.xml
=> Update to latest parent pom 3.33

src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/maven/ReadMavenPomStep/help.html, src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/maven/WriteMavenPomStep/help.html
If #47 is a step too far for @rsandell, can I least document alternate suggestions?
=> Documenting more basic alternatives to the readMavenPom/writeMavenPom steps

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/ZipStep.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/ZipStepExecution.java, src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/zip/ZipStep/config.groovy, src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/zip/ZipStep/help-exclude.html, src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/ZipStepTest.java
Added an exclude option to the zip step. It's just passed through to `Util.createFileSet`.
=> [JENKINS-34734] add exclude option to zip

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadYamlStep.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/csv/ReadCSVStep.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/csv/ReadCSVStepExecution.java, src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadPropertiesStepTest.java, src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/FileSha1StepTest.java
- Ensure closing of file reader, a first approach to [JENKINS-59116](https://issues.jenkins.io/browse/JENKINS-59116)
- Additional test cases for sha1 step
- Some minor enhancements / clean-up
Each of these submitted by separate commits.
=> [JENKINS-59116] Ensure closing of file reader and some enhancements

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/FileHashStep.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/FileSha1Step.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/FileSha256Step.java, src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/fs/FileSha256Step/config.groovy, src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/fs/FileSha256Step/help-file.html, src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/fs/FileSha256Step/help.html, src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/FileSha256StepTest.java
Adds a `sha256` step; with the implementation of `sha256` and `sha1` is extracted to a base class.
------------------
=> sha256 step added

docs/STEPS.md, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/PrependToFileStep.java, src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/fs/PrependToFileStep/config.groovy, src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/fs/PrependToFileStep/help-content.html, src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/fs/PrependToFileStep/help-file.html, src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/fs/PrependToFileStep/help.html, src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/PrependToFileStepTest.java
This PR adds a `prependToFile` build step. While append content to a file is easy with most shells, prepending is harder.
Usage:
```groovy
prependToFile content: 'the content', file: 'my-file.txt'
```
=> Added `prependToFile` step

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadPropertiesStep.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadPropertiesStepExecution.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/tar/UnTarStepExecution.java, src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadYamlStepTest.java
=> Miscellaneous code cleanup

src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/WriteYamlStepTest.java
Verifying something not covered by tests in #105.
=> Verifying that displayed arguments for `writeYaml` does not include YAML content

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/FileVerifyHashStep.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/PrependToFileStep.java
=> EOL JSR 305

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadYamlStep.java, src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadYamlStep/help.groovy
Fixing PR comments #152
Help page now looks like:
=> Fix PR comments

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadYamlStep.java
=> Correct justification text

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/tar/UnTarStep.java, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/tar/UnTarStepExecution.java, src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/tar/UnTarStep/config.groovy, src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/tar/UnTarStep/help-keepPermissions.html, src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/tar/UnTarStepTest.java
Added the option `keepPermissions` to untar step to extract files with their permissions from an archive.
- ~~Link to relevant issues in GitHub or Jira~~
- ~~Link to relevant pull requests, esp. upstream and downstream changes~~
=> Added the option to extract files with their permissions from a tar archive

src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadYamlStep.java, src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadYamlStep/help.groovy, src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadYamlStepTest.java
Use library default, make `MAX_MAX_ALIASES_FOR_COLLECTIONS` final
=> Use library default and make MAX_MAX_ALIASES_FOR_COLLECTIONS final

Jenkinsfile, pom.xml, src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/jenkins/NodesByLabelStep.java
=> Bump core version to 2.361.4 and plugin parent to 4.53

Jenkinsfile
Following the latest archetype.
=> Add Java 17 to build/test matrix

pom.xml
And cleaned up the jackson dependencies (See https://github.com/jenkinsci/pipeline-utility-steps-plugin/pull/272#issuecomment-2658407608) by depending on `jackson2-api-plugin` instead of a direct dependency..
=> Bump plugin parent to 5.7 and jenkins core to 2.492
